wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.6
    start_time: 1644297565
    t:
      1:
      - 1
      - 3
      - 4
      - 5
      2:
      - 1
      - 3
      - 4
      - 5
      3:
      - 13
      - 16
      4: 3.9.6
      5: 0.12.10
      8:
      - 2
      - 5
